project:
  type: website

website:
  title: "analitica-brotes-pe"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Semana 1"
        contents:
          - transmisibilidad-input.qmd
          - transmisibilidad-estimar.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



